sudo: required
services:
 - docker
language: node_js
node_js:
  - "10.14.1"
before_install:
  - commit=$(git log -1 --format="%H")
  - app_version=$(node -e "console.log(require('./package.json').version);")
  - version_prefix=$(echo $commit | head -c 6)
  - app_name=$(node -e "console.log(require('./package.json').name);")
  - author_name="$(git log -1 $TRAVIS_COMMIT --pretty="%aN")"
addons:
  sonarcloud:
    organization: "weslyg-github"
    token:
      secure: ${SONAR_TOKEN}
install:
  # I am started!
  - curl -XPOST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}&parse_mode=MARKDOWN&text=Начинаю сборку \`${app_name}\` версии \`${app_version}-${version_prefix}\`%0A*${author_name}* завез нам - \`${TRAVIS_COMMIT_MESSAGE}\`"
  - npm install
  - npm run build
script:
  - sonar-scanner -Dsonar.projectVersion=${app_version}-${version_prefix}
  - docker build -t $DOCKER_USERNAME/$app_name:$app_version-$version_prefix .
  - docker tag $DOCKER_USERNAME/$app_name:$app_version-$version_prefix weslyg/$app_name:latest
  - docker images
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/$app_name:$app_version-$version_prefix
  - docker push $DOCKER_USERNAME/$app_name:latest
  # I am finished!
  - curl -XPOST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage?chat_id=${TELEGRAM_CHAT_ID}&parse_mode=MARKDOWN&text=Успешно собрал \`${app_name}\` версии \`${app_version}-${version_prefix}\`%0A\[Контейнеры тут\](https://hub.docker.com/r/${DOCKER_USERNAME}/${app_name})%0A\[Commit\](https://github.com/WeslyG/WeekEndChallenge-front/commit/${commit})%0A\[Build\](${TRAVIS_BUILD_WEB_URL})%0A\[SonarQube\](https://sonarcloud.io/dashboard?id=WeekEndChallenge)"